#
# use:    JoseQuintas/harbour_34/hb34_0703
# create: oohg_hb34_mingw_0703
#

name: OOHG Harbour 3.4 mingw 7.3 32/64 bits

on:
  push:
  schedule:
   - cron: "30 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 7.3'
        default: 'oohg_hb34_mingw_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Load Mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: hb34_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: Unzip
      run: |
         c:
         dir c:\temp
         md c:\temp\harbour
         7z x -y c:\temp\hb34_0703.7z -oc:\temp\harbour

    - name: Install Source Code
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         md \temp\harbour\addons
         git clone https://github.com/JoseQuintas/oohg_core c:\temp\harbour\addons\oohg\ --depth 1
         git clone https://github.com/$env:repo c:\temp\harbour\addons\oohg\ofmt --depth 1

    - name: Build 32 bits
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
      run: |
         c:
         cd c:\temp\harbour\addons\oohg
         hbmk2 *.hbp -q -workdir=c:\temp oohg.hbc
         cd \temp\harbour\addons\oohg\ofmt
         hbmk2 *.hbp -q -workdir=c:\temp oohg.hbc

    - name: Build 64 bits
      env:
         HB_COMPILER: mingw64
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\harbour\comp\mingw64\bin
      run: |
         c:
         cd \temp\harbour\addons\oohg
         hbmk2 *.hbp -q -workdir=c:\temp oohg.hbc
         cd \temp\harbour\addons\oohg\ofmt
         hbmk2 *.hbp -q -workdir=c:\temp oohg.hbc

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\harbour
         7z a -r c:\temp\oohg_hb34_mingw_0703.7z c:\temp\harbour\addons\oohg\*.*  -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save
      uses: actions/upload-artifact@v2
      with:
         name: oohg_hb34_mingw_0703
         path: c:\temp\oohg_hb34_mingw_0703.7z
